# Lint config pinned to golangci-lint v2.7.x (see Makefile GOLANGCI_LINT_VERSION).
version: 2

run:
  timeout: 3m
  tests: true
  skip-dirs:
    - vendor
    - fixtures
    - tests/fixtures
    - testdata
  skip-files:
    - ".*_mock.go"
    - "mock_.*\\.go"
    - "zz_generated.*\\.go"

linters:
  preset: recommended
  enable:
    - unused

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
